# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-31 04:59
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPlayers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('desc', models.CharField(max_length=250)),
                ('startDate', models.DateField()),
                ('numberOfPlayers', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sportName', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='SportsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Not Mentioned')], max_length=1)),
                ('birthDate', models.DateField()),
                ('phoneNumber', models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('oneLinerStatus', models.CharField(max_length=140)),
                ('location', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.Location')),
                ('sports', models.ManyToManyField(null=True, to='Core.Sports')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='sports',
            name='sportType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.SportsType'),
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together=set([('country', 'state', 'region')]),
        ),
        migrations.AddField(
            model_name='events',
            name='location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Core.Location'),
        ),
        migrations.AddField(
            model_name='events',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='events',
            name='sport',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Core.Sports'),
        ),
        migrations.AddField(
            model_name='eventplayers',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Core.Events'),
        ),
        migrations.AddField(
            model_name='eventplayers',
            name='players',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
